In [ ]:
#Task1
# Write a program that allows you to enter 4 numbers and stores them in a file called “Numbers”
#•	3
#•  45
#•	83
#•	21
#Have a go at ‘w’ ‘r’  ‘a’

myfile = open("numbers.txt", "w")

def write_to_file(y):
    if (y == 3):
        myfile.write("3,")
    if (y == 45):
        myfile.write( "45,")
    if (y == 83):
        myfile.write("83,")
    if (y == 21):
        myfile.write("21,")
    else:
        print ("Enter a better number try either 3, 45, 83 or 21")

for y in range(4):
    write_to_file(int(input("Enter a number:")))
    

with open ("numbers.txt", "r") as myfile:
    data = myfile.read().replace(',', '\n')

print(data)

with open("numbers.txt", "a") as myfile:
    append_file = myfile.write("number list is now complete")

with open ("numbers.txt", "r") as myfile:
    read_file = myfile.read()
print(read_file)

myfile.close()

In [ ]:
#Task2
# Write a program to ask a student for their percentage mark and convert this to a grade.
#The conversion will be done in a function called mark_grade

def mark_grade(grade):
    if (grade > 80):
        print ("Your grade is A")
    if (grade > 60):
        print ("Your grade is B")
    if (grade > 40):
        print ("Your grade is C")
    if (grade > 20):
        print ("Your grade is D")
    if (grade > 10):
        print ("Your grade is E")
    return grade

mark_grade(int(input("Enter your percentage mark")))
   

In [ ]:
#Task2 Extension
#•	Ask the user for their target grade and print this with their mark
#•	If their target grade > exam grade display a suitable message
#•	If their target grade = exam grade display a suitable message
#•	If their target grade < exam grade display a suitable message

def target_grade(target):
    if (target == mark_grade):
        print ("You met your target grade")
    if (target > mark_grade):
        print ("You overachieved your target grade")
    if (target < mark_grade):
        print ("You underachived your grade")

target_grade(input("Enter your target grade"))

In [54]:
#1.	Create a 1D array of numbers from 0 to 9
#2.	Create a 3×3 NumPy array of all Boolean value Trues
#3.	Extract all odd numbers from array of 1-10
#4.	Replace all odd numbers in an array of 1-10 with the value -1
#5.	Convert a 1D array to a 2D array with 2 rows
#6.	Create two arrays a and b, stack these two arrays vertically use the  np.dot and np.sum to calculate totals

import numpy as np

#1
array = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
print("Task #1")
print(array)

#2 

boolean_array = np.ones((3,3), dtype=bool)
print("Task #2")
print(boolean_array)

#3
array2 = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
array3 = array2[array2%2==0]
print("Task #3")
print(array3)

#4 

array2[array2%2 == 1] = -1 
print("Task #4")
print(array2)

#5

array4 = array.reshape(2, 5)
print("Task #5")
print (array4)

#6

a = np.arange(1,10).reshape(3,3)
b = np.arange(10,19).reshape(3,3)
c = np.vstack((a,b))
d = np.dot(a,b)
print("Task #5")
print(c)
print (d)
sum = np.sum (d)
print (sum)

Task #1
[0 1 2 3 4 5 6 7 8 9]
Task #2
[[ True  True  True]
 [ True  True  True]
 [ True  True  True]]
Task #3
[ 2  4  6  8 10]
Task #4
[-1  2 -1  4 -1  6 -1  8 -1 10]
Task #5
[[0 1 2 3 4]
 [5 6 7 8 9]]
Task #5
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]
 [13 14 15]
 [16 17 18]]
[[ 84  90  96]
 [201 216 231]
 [318 342 366]]
1944


In [ ]:
#1.	Create the following pattern without hardcoding. Use only NumPy  functions.
#array ([1,1,1,2,2,2,3,3,3,1,2,3,1,2,3,1,2,3])
#2.	In two arrays a ( 1,2,3,4,5) and b ( 4,5,6,7,8,9) – remove all repeating  items present in array b
#3.	Get all items between 3 and 7 from a and b and sum them together

e_array = np.ones(3)